version: "3"

services:
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        restart: unless-stopped
        image: mysql:${MYSQL_VERSION}
        ports:
            - "3306:3306"
        volumes:
            - ~/apps/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - symfony_app
#    postgres:
#        container_name: ${COMPOSE_PROJECT_NAME}_postgres
#        restart: unless-stopped
#        image: postgres:14-alpine
#        ports:
#            - "5432:5432"
#        volumes:
#            - ~/apps/postgres:/var/lib/postgresql/data
#        environment:
#            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#            POSTGRES_USER: ${POSTGRES_USER}
#            POSTGRES_DB: ${POSTGRES_DB}
#        networks:
#            - symfony_app
    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        restart: unless-stopped
        env_file:
            - .env
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../backend/:/var/www/symfony:cached
            - .env:/var/www/symfony/.env
        #            - symfony_app_var:/var/www/symfony/var
        #            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app
    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        restart: unless-stopped
        build:
            context: ./nginx
        volumes:
            - ../backend/:/var/www/symfony
        #            - symfony_app_var:/var/www/symfony/var
        #            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - "80:80"
        networks:
            - symfony_app

volumes:
    symfony_app_var:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ../backend/var
    symfony_app_vendor:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ../backend/vendor

networks:
    symfony_app:
        driver: bridge
